//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papamamaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class practicaEntities2 : DbContext
    {
     
        private static practicaEntities2 context;
        public practicaEntities2()
            : base("name=practicaEntities2")
        {
        }

        public static practicaEntities2 GetContext()
        {
            if (context == null)
                context = new practicaEntities2();
            return context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cvet> cvet { get; set; }
        public virtual DbSet<cvet1> cvet1 { get; set; }
        public virtual DbSet<furnitura> furnitura { get; set; }
        public virtual DbSet<furnitura_izdeliya> furnitura_izdeliya { get; set; }
        public virtual DbSet<furnituraizdeliya> furnituraizdeliya { get; set; }
        public virtual DbSet<izdeliya> izdeliya { get; set; }
        public virtual DbSet<risunok> risunok { get; set; }
        public virtual DbSet<risunoktkani> risunoktkani { get; set; }
        public virtual DbSet<skladfurniturra> skladfurniturra { get; set; }
        public virtual DbSet<skladtkani> skladtkani { get; set; }
        public virtual DbSet<sostav> sostav { get; set; }
        public virtual DbSet<sostavtkani> sostavtkani { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tcanicvet> tcanicvet { get; set; }
        public virtual DbSet<tip> tip { get; set; }
        public virtual DbSet<tipfurnitura> tipfurnitura { get; set; }
        public virtual DbSet<tkan1> tkan1 { get; set; }
        public virtual DbSet<tkani> tkani { get; set; }
        public virtual DbSet<tkani_izdeliya> tkani_izdeliya { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
        public virtual DbSet<zakazan_izdeliya> zakazan_izdeliya { get; set; }
    }
}
