//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papamamaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovari
    {
        public int articul { get; set; }
        public string name { get; set; }
        public string size { get; set; }
        public string cvet { get; set; }
        public string sostav { get; set; }
        public string prod { get; set; }
        public Nullable<int> cena { get; set; }
    }
}
