//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papamamaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int ID { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string zakazchik { get; set; }
        public string manager { get; set; }
        public string status { get; set; }
    }
}
